### ISSUE TITLE
TypeError: Cannot read property 'timeout' of undefined

### ISSUE THREAD

**Issue by grantchiu011101** [triploc/ib-sdk#5]
when i initial sdk env. with `sdk.environment("./config/default.json", (err, ib) => {})`.
It doesnt work and  got `Cannot read property 'timeout' of undefined`

After investigate you code
I found that you should use sync call when reading config file.

**Comment by grantchiu011101** [comment]
https://github.com/triploc/ib-sdk/pull/6

here is the pull commit for this fix

**Comment by grantchiu011101** [comment]
https://github.com/triploc/ib-sdk/pull/6

**Comment by zgsrc** [comment]
Grant,
Thank you for your feedback and corrections.  Very valuable.  I want you to know
in advance that the "model" portion of the code is undergoing a major refactor
and significant changes will be introduced in version 0.6.
Best,Jonathan  





On Tue, Jun 13, 2017 6:55 AM, Grant Fong notifications@github.com  wrote:
#6

**Comment by grantchiu011101** [comment]
Thanks you Jonathan. That's great~
Looking forward for the change! 👍 

Your code is elegant and I can provide any help if you need it
